[package]
name = "btrbk_tui"
version = "2.2.0"
edition = "2024"

[dependencies]
ncurses = "5.101.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0"
libc = "0.2"
